---
- name: Install and configure MariaDB on Ubuntu
  hosts: all
  become: true
  vars:
    mariadb_root_password: "9jKYgO*8$8c7xoncF@C2"
    mariadb_bind_address: "0.0.0.0"  # Change to desired IP address for remote connections

  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install dependencies for wordpress 
      apt:
        name:  
          - apache2
          - ghostscript
          - libapache2-mod-php
          - mysql-server
          - php
          - php-bcmath
          - php-curl
          - php-imagick
          - php-intl
          - php-json
          - php-mbstring
          - php-mysql
          - php-xml
          - php-zip
          - curl
          - wordpress
        state: present

    - name: Create folder /srv/www
      file:
        path: /srv/www
        state: directory
        mode: '0755'

    - name: Change owner of /srv/www to www-data
      file:
        path: /srv/www
        owner: www-data
        group: www-data
        recurse: yes

    - name: Download latest WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /srv/www/latest.tar.gz
        owner: www-data
        group: www-data

    - name: Extract latest WordPress
      unarchive:
        src: /srv/www/latest.tar.gz
        dest: /srv/www
        remote_src: yes
        owner: www-data
        group: www-data

    - name: Copy wordpress.conf to /etc/apache2/sites-available/wordpress.conf
      copy:
        src: wordpress.conf
        dest: /etc/apache2/sites-available/wordpress.conf
        owner: root
        group: root
        mode: '0644'

    - name: Enable wordpress site
      command: sudo a2ensite wordpress

    - name: Enable rewrite module
      command: sudo a2enmod rewrite

    - name: Disable default site
      command: sudo a2dissite 000-default

    - name: Disable default site
      command: sudo service apache2 reload